server:
  port: 8080
info:
  app:
    name: Bootapps Dashboard
    version: 1.0-SNAPSHOT
    deploydate: 2018-10-26T10:13:57+00:00
dashboard:
  autoreload: false
  autoreload-interval: 30000
  bootapps:
    - id: bootapps-dashboard
      health-endpoint-url: http://localhost:8080/actuator/health
      info-endpoint-url: http://localhost:8080/actuator/info
    - id: demo-app
      health-endpoint-url: http://localhost:8081/actuator/health
      health-endpoint-username: user
      health-endpoint-password: password
      info-endpoint-url: http://localhost:8081/actuator/info
      info-endpoint-username: user
      info-endpoint-password: password